// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: message.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UDPMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIP        string                 `protobuf:"bytes,1,opt,name=fromIP,proto3" json:"fromIP,omitempty"`
	FromPort      int32                  `protobuf:"varint,2,opt,name=fromPort,proto3" json:"fromPort,omitempty"`
	ToIP          string                 `protobuf:"bytes,3,opt,name=toIP,proto3" json:"toIP,omitempty"`
	ToPort        int32                  `protobuf:"varint,4,opt,name=toPort,proto3" json:"toPort,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPMessage) Reset() {
	*x = UDPMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPMessage) ProtoMessage() {}

func (x *UDPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPMessage.ProtoReflect.Descriptor instead.
func (*UDPMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *UDPMessage) GetFromIP() string {
	if x != nil {
		return x.FromIP
	}
	return ""
}

func (x *UDPMessage) GetFromPort() int32 {
	if x != nil {
		return x.FromPort
	}
	return 0
}

func (x *UDPMessage) GetToIP() string {
	if x != nil {
		return x.ToIP
	}
	return ""
}

func (x *UDPMessage) GetToPort() int32 {
	if x != nil {
		return x.ToPort
	}
	return 0
}

func (x *UDPMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\anetwork\"\x86\x01\n" +
	"\n" +
	"UDPMessage\x12\x16\n" +
	"\x06fromIP\x18\x01 \x01(\tR\x06fromIP\x12\x1a\n" +
	"\bfromPort\x18\x02 \x01(\x05R\bfromPort\x12\x12\n" +
	"\x04toIP\x18\x03 \x01(\tR\x04toIP\x12\x16\n" +
	"\x06toPort\x18\x04 \x01(\x05R\x06toPort\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayloadB\fZ\n" +
	"./;networkb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*UDPMessage)(nil), // 0: network.UDPMessage
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
