// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: node_info_message.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	ID            []byte                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoMessage) Reset() {
	*x = NodeInfoMessage{}
	mi := &file_node_info_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoMessage) ProtoMessage() {}

func (x *NodeInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_node_info_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoMessage.ProtoReflect.Descriptor instead.
func (*NodeInfoMessage) Descriptor() ([]byte, []int) {
	return file_node_info_message_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfoMessage) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *NodeInfoMessage) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfoMessage) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

var File_node_info_message_proto protoreflect.FileDescriptor

const file_node_info_message_proto_rawDesc = "" +
	"\n" +
	"\x17node_info_message.proto\x12\x06common\"E\n" +
	"\x0fNodeInfoMessage\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\x05R\x04Port\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\fR\x02IDB\vZ\t./;commonb\x06proto3"

var (
	file_node_info_message_proto_rawDescOnce sync.Once
	file_node_info_message_proto_rawDescData []byte
)

func file_node_info_message_proto_rawDescGZIP() []byte {
	file_node_info_message_proto_rawDescOnce.Do(func() {
		file_node_info_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_info_message_proto_rawDesc), len(file_node_info_message_proto_rawDesc)))
	})
	return file_node_info_message_proto_rawDescData
}

var file_node_info_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_info_message_proto_goTypes = []any{
	(*NodeInfoMessage)(nil), // 0: common.NodeInfoMessage
}
var file_node_info_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_info_message_proto_init() }
func file_node_info_message_proto_init() {
	if File_node_info_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_info_message_proto_rawDesc), len(file_node_info_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_info_message_proto_goTypes,
		DependencyIndexes: file_node_info_message_proto_depIdxs,
		MessageInfos:      file_node_info_message_proto_msgTypes,
	}.Build()
	File_node_info_message_proto = out.File
	file_node_info_message_proto_goTypes = nil
	file_node_info_message_proto_depIdxs = nil
}
