// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: node_info_message_list.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfoMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfoMessage     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoMessageList) Reset() {
	*x = NodeInfoMessageList{}
	mi := &file_node_info_message_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoMessageList) ProtoMessage() {}

func (x *NodeInfoMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_node_info_message_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoMessageList.ProtoReflect.Descriptor instead.
func (*NodeInfoMessageList) Descriptor() ([]byte, []int) {
	return file_node_info_message_list_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfoMessageList) GetNodes() []*NodeInfoMessage {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_node_info_message_list_proto protoreflect.FileDescriptor

const file_node_info_message_list_proto_rawDesc = "" +
	"\n" +
	"\x1cnode_info_message_list.proto\x12\x06common\x1a\x17node_info_message.proto\"D\n" +
	"\x13NodeInfoMessageList\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.common.NodeInfoMessageR\x05nodesB\vZ\t./;commonb\x06proto3"

var (
	file_node_info_message_list_proto_rawDescOnce sync.Once
	file_node_info_message_list_proto_rawDescData []byte
)

func file_node_info_message_list_proto_rawDescGZIP() []byte {
	file_node_info_message_list_proto_rawDescOnce.Do(func() {
		file_node_info_message_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_info_message_list_proto_rawDesc), len(file_node_info_message_list_proto_rawDesc)))
	})
	return file_node_info_message_list_proto_rawDescData
}

var file_node_info_message_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_info_message_list_proto_goTypes = []any{
	(*NodeInfoMessageList)(nil), // 0: common.NodeInfoMessageList
	(*NodeInfoMessage)(nil),     // 1: common.NodeInfoMessage
}
var file_node_info_message_list_proto_depIdxs = []int32{
	1, // 0: common.NodeInfoMessageList.nodes:type_name -> common.NodeInfoMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_info_message_list_proto_init() }
func file_node_info_message_list_proto_init() {
	if File_node_info_message_list_proto != nil {
		return
	}
	file_node_info_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_info_message_list_proto_rawDesc), len(file_node_info_message_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_info_message_list_proto_goTypes,
		DependencyIndexes: file_node_info_message_list_proto_depIdxs,
		MessageInfos:      file_node_info_message_list_proto_msgTypes,
	}.Build()
	File_node_info_message_list_proto = out.File
	file_node_info_message_list_proto_goTypes = nil
	file_node_info_message_list_proto_depIdxs = nil
}
